"""
    CRIE UM PROGRAMA QUE LEIA NOME, ANO DE NASCIMENTO E CARTEIRA DE TRABALHO
    E CADASTRE-OS(COM IDADE) EM UM DICIONÁRIO CASO O CTPS FOR DIFERENTE DE ZERO,
    O DICIONÁRIO RECEBERÁ TAMBÉM O ANO DE CONTRATAÇÃO E O SALÁRIO.
    CALCULE E ACRESCENTE, ALÉM DA IDADE, COM QUANTOS ANOS A PESSOA VAI SE
    APOSENTAR.
"""