"""
    CRIE UM PROGRAMA QUE GERENCIE O APROVEITAMENTO DE UM JOGADOR DE FUTEBOL.
    O PROGRAMA VAI LER O NOME DO JOGADOR E QUANTAS PARTIDAS ELE JOGOU.
    DEPOIS VAI LER A QUANTIDADE DE GOLS FEITOS EM CADA PARTIDA.
    NO FINAL, TUDO ISSO SERÁ GUARDADO EM UM DICIONÁRIO, INCLUINDO
    O TOTAL DE GOLS FEITOS DURANTE O CAMPEONATO.
"""