"""
    CRIE UM PROGRAMA QUE LEIA O NOME, SEXO E A IDADE DE VÁRIAS PESSOAS,
    GUARDANDO OS DADOS DE CADA PESSOA EM UM DICIONÁRIO E TODOS OS
    DICIONÁRIOS EM UMA LISTA. NO FINAL, MOSTRE:
    A) QUANTAS PESSOAS FORAM CADASTRADAS
    B) A MÉDIA DE IDADE DO GRUPO
    C) UMA LISTA COM TODAS AS MULHERES
    D) UMA LISTA COM TODAS AS PESSOAS COM IDADE ACIMA DA MÉDIA
"""