"""
    CRIE UM PEQUENO SISTEMA MODULARIZADO QUE PERMITE CADASTRAR PESSOAS PELO SEU NOME E IDADE
    EM UM ARQUIVO DE TEXTO SIMPLES.

    O SISTEMA SÓ VAI TER 2 OPÇÕES: CADASTRAR UMA NOVA PESSOA E LISTAR TODAS AS PESSOAS CADASTRADAS.


    OPÇÕES PARA MANIPULAÇÃO DE ARQUIVOS PYTHON

    'r' ==> LEITURA
    'w' ==> ESCRITA. SUBSTITUI O CONTEÚDO DO ARQUIVO EXISTENTE
    'x' ==> ESCRITA. RETORNA ERRO CASO O ARQUIVO JÁ EXISTA
    'a' ==> ESCRITA. INSERE OS NOVOS DADOS NO FINAL DO ARQUIVO
    'b' ==> MONO BINÁRIO
    't' ==> MODO DE TEXTO (PADRÃO)
    '+' ==> ATUALIZAR. TANTO LEITURA QUANTO ESCRITA

"""





