"""
    CRIE UM PROGRAMA ONDE O USUÁRIO DIGITE UMA EXPRESSÃO
    QUALQUER QUE USE PARÊNTESES. SEU APLICATIVO DEVERÁ
    ANALISAR SE A EXPRESSÃO ESTÁ COM OS PARÊNTESES ABERTOS
    E FECHADOS NA ORDEM CORRETA.
"""