"""
    CRIE UM PROGRAMA QUE TENHA UMA FUNÇÃO LEIAINT(), QUE VAI FUNCIONAR DE FORMA SEMELHANTE
    A FUNÇÃO INPUT() DO PYTHON, SÓ QUE FAZENDO A VALIDAÇÃO PARA ACEITAR APENAS UM VALOR NÚMERICO.

    EX.:

    n = leiaInt('DIGITE UM VALOR PARA N: ')
"""