"""
    FAÇA UM MINI-SISTEMA QUE UTILIZA O INTERACTIVE HELP DO PYTHON.
    O USUÁRIO VAI DIGITAR O COMANDO E O MANUAL VAI APARECER.

    QUANDO O USUÁRIO DIGITAR A PALAVRA 'FIM', O PROGRAMA SE ENCERRARÁ.

    OBS.: USE CORES.
"""